name: Spinalpack
main: com.spinalcraft.spinalpack.Spinalpack
version: 1.0

commands:
  spinalpack:
    description: Access Spinalpack commands
    usage: Usage - /spinalpack unpack
    permission: spinalpack.unpack
    permission-message: No touchy.