name: Spinalpack
main: com.spinalcraft.spinalpack.Spinalpack
version: 1.0

commands:
  rules:
    description: Get information about Spinalcraft's rules
    usage: Usage - /rules
    permission: spinalpack.rules
    permission-message: No!