name: Spinalpack
main: com.spinalcraft.spinalpack.Spinalpack
version: 1.0

commands:
  rules:
    description: Get information about Spinalcraft's rules
    usage: Usage - /rules
    permission: spinalpack.rules
    permission-message: No!
  report:
    description: Report an issue to the mods
    usage: Usage - /report
    permission: spinalpack.report
    permission-message: No!
  setdonor:
    description: Give a user donor privileges
    usage: Usage - /setdonor <username>
    permission: spinalpack.setdonor
    permission-message: No!